config/routes.rb
Rails.application.routes.draw do
  get "admin" => "admin#index"
  resources :users
  resource :session
  resources :passwords, param: :token
  resources :products

  resources :support_requests, only: %i[index update]

  scope "(:locale)" do
    resources :orders
    resources :line_items
    resources :carts
    root "store#index", as: "store_index", via: :all
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/order.rb
require "pago"

class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :support_requests, dependent: :nullify

  enum :pay_type, {
    "Check"           => 0,
    "Credit card"     => 1,
    "Purchase order"  => 2
  }

  validates :address, :email, :name, presence: true
  validates :pay_type, inclusion: pay_types.keys

  validates :credit_card_number, :expiration_date, presence: true, if: -> { pay_type == "Credit card" }
  validates :routing_number, :account_number, presence: true, if: -> { pay_type == "Check" }
  validates :po_number, presence: true, if: -> { pay_type == "Purchase order" }

  def add_line_items_from_cart(cart)
    cart.line_items.each do |li|
      li.cart_id = nil
      line_items << li
    end
  end

  def charge!
    payment_details = {}
    payment_method = nil

    case pay_type
    when "Check"
      payment_method = :check
      payment_details[:routing] = routing_number
      payment_details[:account] = account_number
    when "Credit card"
      payment_method = :credit_card
      payment_details[:cc_num] = credit_card_number
      payment_details[:expiration_month] = expiration_date.month
      payment_details[:expiration_year] = expiration_date.year
    when "Purchase order"
      payment_method = :po
      payment_details[:po_num] = po_number
    end

    payment_result = Pago.make_payment(
      order_id: id,
      payment_method: payment_method,
      payment_details: payment_details
    )

    if payment_result.succeeded?
      OrderMailer.received(self).deliver_later
    else
      raise payment_result.error
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentCart

  allow_unauthenticated_access only: %i[ new create ]

  before_action :set_cart, only: %i[ new create ]
  before_action :ensure_cart_isnt_empty, only: %i[ new ]
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)

    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil

        ChargeOrderJob.perform_later(@order)

        format.html { redirect_to store_index_path(locale: I18n.locale), notice: I18n.t(".thanks") }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy!

    respond_to do |format|
      format.html { redirect_to orders_path, status: :see_other, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def order_params
      base_params = params.require(:order).permit(:name, :address, :email, :pay_type)

      case base_params[:pay_type]
      when "Credit card"
        base_params.merge!(params.require(:order).permit(:credit_card_number, :expiration_date))
      when "Check"
        base_params.merge!(params.require(:order).permit(:routing_number, :account_number))
      when "Purchase order"
        base_params.merge!(params.require(:order).permit(:po_number))
      end

      base_params
    end

    def ensure_cart_isnt_empty
      if @cart.line_items.empty?
        redirect_to store_index_path, notice: "Your cart is empty."
      end
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_cc.html.erb
<fieldset data-payment-target="additionalFields" data-type="Credit card">
  <div class="my-5">
    <%= form.label :credit_card_number, t(".cc_number") %>
    <%= form.password_field :credit_card_number, class: "input-field" %>
  </div>

  <div class="my-5">
    <%= form.label :expiration_date, t(".expiration_date") %>
    <%= form.date_field :expiration_date, class: "input-field", size: 9, placeholder: "e.g. 03/25" %>
  </div>
</fieldset>

app/views/orders/_check.html.erb
<fieldset data-payment-target="additionalFields" data-type="Check">
  <div class="my-5">
    <%= form.label :routing_number, t(".routing_number") %>
    <%= form.text_field :routing_number, class: "input-field" %>
  </div>

  <div class="my-5">
    <%= form.label :account_number, t(".account_number") %>
    <%= form.password_field :account_number, class: "input-field" %> 
  </div> 
</fieldset>

app/views/orders/_form.html.erb
<%= form_with(model: order, class: "contents", url: orders_path(locale: I18n.locale)) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= raw t("errors.template.header", count: order.errors.count, model: t("activerecord.models.order")) %></h2>

      <ul class="list-disc ml-6">
        <% order.errors.each do |error| %>
          <li><%= raw error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, t(".name") %>
    <%= form.text_field :name, class: "input-field" %>
  </div>

  <div class="my-5">
    <%= form.label :address, t(".address_html") %>
    <%= form.textarea :address, rows: 4, class: "input-field" %>
  </div>

  <div class="my-5">
    <%= form.label :email, t(".email") %>
    <%= form.email_field :email, class: "input-field" %>
  </div>

  <div data-controller="payment">
    <div class="my-5">
      <%= form.label :pay_type, t(".pay_type") %>
      <%= form.select :pay_type,
                      Order.pay_types.keys.map { |key| [t(".pay_types.#{key}"), key] },
                      { prompt: t(".pay_prompt_html") }, 
                      "data-payment-target" => "selection",
                      "data-action" => "payment#showAdditionalFields",
                      class: "input-field"
      %>
    </div>

    <%= render partial: "cc", locals: { form: form } %>
    <%= render partial: "po", locals: { form: form } %>
    <%= render partial: "check", locals: { form: form } %>

  </div>

  <div class="inline">
    <%= form.submit t(".submit"), class: "rounded-md px-3.5 py-2.5 bg-green-200 hover:bg-green-500 text-black inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>" class="my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= order.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Address:</strong>
    <%= order.address %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Pay type:</strong>
    <%= order.pay_type %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Email:</strong>
    <%= order.email %>
  </div>
</div>

app/views/orders/_po.html.erb
<fieldset data-payment-target="additionalFields" data-type="Purchase order">
  <div class="my-5">
    <%= form.label :po_number, t(".po_number") %>
    <%= form.number_field :po_number, class: "input-field" %>
  </div>
</fieldset>

app/views/orders/edit.html.erb
<% content_for :title, "Editing order" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing order</h1>

  <%= render "form", order: @order %>

  <%= link_to "Show this order", @order, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to orders", orders_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/orders/index.html.erb
<% content_for :title, "Orders" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Orders</h1>
    <%= link_to "New order", new_order_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="orders" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @orders.any? %>
      <% @orders.each do |order| %>
        <div class="flex justify-between items-center">
          <%= render order %>
          <div class="space-x-2">
            <%= link_to "Show", order_path(id: order.id), class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_order_path(id: order.id), class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <div class="inline-block">
              <%= button_to "Destroy", order_path(id: order.id), method: :delete, class: "rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No orders found.</p>
    <% end %>
  </div>
</div>

app/views/orders/new.html.erb
<% content_for :title, "New order" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= t(".legend") %></h1>

  <%= render "form", order: @order %>
</div>

app/views/orders/show.html.erb
<% content_for :title, "Showing order" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing order</h1>

  <%= render @order %>

  <%= link_to "Edit this order", edit_order_path(@order), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to orders", orders_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this order", @order, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>