config/routes.rb
Rails.application.routes.draw do
  get "admin" => "admin#index"
  resources :users
  resource :session
  resources :passwords, param: :token
  resources :products

  resources :support_requests, only: %i[index update]

  scope "(:locale)" do
    resources :orders
    resources :line_items
    resources :carts
    root "store#index", as: "store_index", via: :all
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart, optional: true
  belongs_to :order, optional: true

  def total_price
    quantity * price
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include Counter
  include CurrentCart

  allow_unauthenticated_access only: %i[ create destroy ]

  before_action :set_cart, only: %i[ create destroy ]
  before_action :set_line_item, only: %i[ show edit update destroy ]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_line_item

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)

    respond_to do |format|
      if @line_item.save
        reset_counter

        format.turbo_stream { @current_item = @line_item }
        format.html { redirect_to store_index_url }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    if @line_item.quantity > 1
      @line_item.quantity -= 1
      @line_item.save!
    else
      @line_item.destroy!
    end

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to store_index_path, status: :see_other, notice: "Line item was successfully removed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.expect(line_item: [ :product_id ])
    end

    def invalid_line_item
      logger.error "Attempt to access invalid line item #{ params[:id] }"
      redirect_to store_index_url, notice: "Invalid line item"
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, class: "contents") do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul class="list-disc ml-6">
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :product_id %>
    <%= form.text_field :product_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": line_item.errors[:product_id].none?, "border-red-400 focus:outline-red-600": line_item.errors[:product_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": line_item.errors[:cart_id].none?, "border-red-400 focus:outline-red-600": line_item.errors[:cart_id].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
<tr class="line-item-highlight h-12">
<% else %>
<tr class="h-12">
<% end %>
    <td class="text-right"><%= line_item.quantity %></td>
    <td>&times;</td>
    <td class="pr-2"><%= line_item.product.title %></td>
    <td class="text-right font-bold"><%= number_to_currency line_item.total_price %></td>
    <% if defined?(line_item_path) %>
      <td><%= button_to "–", line_item_path(id: line_item.id), method: :delete, class: "py-1 px-2 bg-red-600 rounded-lg text-white ml-4 cursor-pointer" %></td>
    <% else %>
      <td></td>
    <% end %>
</tr>

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s",
  line_item.quantity,
  truncate(line_item.product.title, length: 50))
%>

app/views/line_items/create.turbo_stream.erb
<%= turbo_stream.replace "notice" do %>
    <%= render partial: "store/notice" %>
<% end %>

<%= turbo_stream.replace "cart" do %>
    <%= render partial: "layouts/cart", locals: { cart: @cart } %>
<% end %>

app/views/line_items/destroy.turbo_stream.erb
<%= turbo_stream.replace "notice" do %>
    <%= render partial: "store/notice" %>
<% end %>

<%= turbo_stream.replace "cart" do %>
    <%= render partial: "layouts/cart", locals: { cart: @cart } %>
<% end %>

app/views/line_items/edit.html.erb
<% content_for :title, "Editing line item" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing line item</h1>

  <%= render "form", line_item: @line_item %>

  <%= link_to "Show this line item", @line_item, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to line items", line_items_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/line_items/index.html.erb
<% content_for :title, "Line items" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Line items</h1>
    <%= link_to "New line item", new_line_item_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="line_items" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @line_items.any? %>
      <% @line_items.each do |line_item| %>
        <div class="flex justify-between items-center">
          <%= render line_item %>
          <div class="space-x-2">
            <%= link_to "Show", line_item, class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_line_item_path(line_item), class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <div class="inline-block">
              <%= button_to "Destroy", line_item, method: :delete, class: "rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No line items found.</p>
    <% end %>
  </div>
</div>

app/views/line_items/new.html.erb
<% content_for :title, "New line item" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New line item</h1>

  <%= render "form", line_item: @line_item %>

  <%= link_to "Back to line items", line_items_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/line_items/show.html.erb
<% content_for :title, "Showing line item" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing line item</h1>

  <%= render @line_item %>

  <%= link_to "Edit this line item", edit_line_item_path(@line_item), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to line items", line_items_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this line item", @line_item, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>