config/routes.rb
Rails.application.routes.draw do
  get "admin" => "admin#index"
  resources :users
  resource :session
  resources :passwords, param: :token
  resources :products

  resources :support_requests, only: %i[index update]

  scope "(:locale)" do
    resources :orders
    resources :line_items
    resources :carts
    root "store#index", as: "store_index", via: :all
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_cart.html.erb
<% if cart and cart.line_items.any? %>
  <div id="cart" class="bg-white p-2 rounded">
    <%= render cart %>
  </div>
<% else %>
  <div id="cart"></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Pragprog Books Online Store" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="bg-green-700 flex items-center justify-between">
      <%= image_tag "logo.svg", alt: "The Pragmatic Bookshelf" %>
      <h1><%= @page_title %></h1>
      <aside data-controller="locale">
        <%= form_with url: store_index_path, class: "mr-4" do %>
          <%= select_tag "set_locale",
            options_for_select(LANGUAGES, I18n.locale.to_s),
            class: "text-white",
            onchange: "this.form.submit()" 
          %>
          <%= submit_tag "submit", data: { "locale-target" => "submit" } %>
        <% end %>
      </aside>
    </header>
    <section class="flex">
      <nav class="bg-green-900 p-6">
        <%= render partial: "layouts/cart", locals: { cart: @cart } %>

        <ul class="text-gray-300 leading-8">
          <li><%= link_to t(".home"), store_index_path(locale: I18n.locale) %></li>
          <li><a href="/questions"><%= t(".questions") %></a></li>
          <li><a href="/news"><%= t(".news") %></a></li>
          <li><a href="/contact"><%= t(".contact") %></a></li>
          <li class="mt-8 text-xs"><%= l Time.now, format: :short %></li>
        </ul>

        <hr class="my-2">

        <ul class="text-gray-300 leading-8">
        <% if authenticated? %>
          <li><%= link_to "Orders", orders_path %></li>
          <li><%= link_to "Products", products_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= button_to "Logout", session_path, method: :delete, class: 'cursor-pointer' %></li>
        <% else %>
          <li><%= link_to "Login", new_session_path %></li>
        <% end %>
        </ul>
      </nav>

      <main class="container mx-auto mt-4 px-5 flex">
        <%= yield %>
      </main>
    </section>
  </body>
</html>